const STORAGE_KEY = 'studyflow-tasks';
let tasks = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]');
let activeFilter = 'all';
let editingTaskId = null;
const $ = selector => document.querySelector(selector);
const elements = { taskList: $('#taskList'), emptyState: $('#emptyState'), emptyTitle: $('#emptyTitle'), emptyText: $('#emptyText'), searchInput: $('#searchInput'), modal: $('#modal'), taskForm: $('#taskForm'), titleInput: $('#titleInput'), descriptionInput: $('#descriptionInput'), priorityInput: $('#priorityInput'), dueDateInput: $('#dueDateInput'), modalTitle: $('#modalTitle'), saveButton: $('#saveButton'), totalCount: $('#totalCount'), completedCount: $('#completedCount'), pendingCount: $('#pendingCount'), highCount: $('#highCount'), taskSummary: $('#taskSummary') };
function saveTasks() { localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks)); }
function formatDate(dateString) { return new Date(`${dateString}T00:00:00`).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' }); }
function escapeHtml(value) { const div = document.createElement('div'); div.textContent = value; return div.innerHTML; }

// Render the filtered task list and keep the dashboard statistics current.
function render() {
	const searchTerm = elements.searchInput.value.trim().toLowerCase();
	const visibleTasks = tasks.filter(task => (activeFilter === 'all' || (activeFilter === 'completed' ? task.completed : !task.completed)) && task.title.toLowerCase().includes(searchTerm));
	elements.taskList.innerHTML = visibleTasks.map(task => `<article class="task-card ${task.completed ? 'completed' : ''}"><button class="check-button" data-action="toggle" data-id="${task.id}" aria-label="Mark task ${task.completed ? 'pending' : 'completed'}">${task.completed ? '&#10003;' : ''}</button><div class="task-main"><h3>${escapeHtml(task.title)}</h3>${task.description ? `<p>${escapeHtml(task.description)}</p>` : ''}<div class="task-meta"><span class="priority ${task.priority}">${task.priority}</span><span>&#128197; ${formatDate(task.dueDate)}</span></div></div><div class="task-actions"><button class="icon-button" data-action="edit" data-id="${task.id}" aria-label="Edit task">&#9998;</button><button class="icon-button" data-action="delete" data-id="${task.id}" aria-label="Delete task">&#128465;</button></div></article>`).join('');
	elements.emptyState.hidden = visibleTasks.length > 0;
	elements.emptyTitle.textContent = tasks.length ? 'No matching tasks' : 'No tasks yet'; elements.emptyText.textContent = tasks.length ? 'Try another search or switch to a different filter.' : 'Add your first task and turn your plans into progress.';
	const completed = tasks.filter(task => task.completed).length; elements.totalCount.textContent = tasks.length; elements.completedCount.textContent = completed; elements.pendingCount.textContent = tasks.length - completed; elements.highCount.textContent = tasks.filter(task => task.priority === 'high' && !task.completed).length; elements.taskSummary.textContent = tasks.length ? `${tasks.length} task${tasks.length === 1 ? '' : 's'} in your workspace` : 'Stay on top of your next steps.';
}
function openModal(task = null) { editingTaskId = task ? task.id : null; elements.modalTitle.textContent = task ? 'Edit task' : 'Add a new task'; elements.saveButton.textContent = task ? 'Update task' : 'Save task'; elements.titleInput.value = task?.title || ''; elements.descriptionInput.value = task?.description || ''; elements.priorityInput.value = task?.priority || 'medium'; elements.dueDateInput.value = task?.dueDate || ''; $('#titleError').textContent = ''; $('#dateError').textContent = ''; elements.modal.hidden = false; elements.titleInput.focus(); }
function closeModal() { elements.modal.hidden = true; elements.taskForm.reset(); editingTaskId = null; }
elements.taskList.addEventListener('click', event => { const button = event.target.closest('[data-action]'); if (!button) return; const task = tasks.find(item => item.id === button.dataset.id); if (button.dataset.action === 'toggle') task.completed = !task.completed; if (button.dataset.action === 'delete') tasks = tasks.filter(item => item.id !== button.dataset.id); if (button.dataset.action === 'edit') { openModal(task); return; } saveTasks(); render(); });
elements.taskForm.addEventListener('submit', event => { event.preventDefault(); const title = elements.titleInput.value.trim(); const dueDate = elements.dueDateInput.value; let valid = true; $('#titleError').textContent = ''; $('#dateError').textContent = ''; if (!title) { $('#titleError').textContent = 'Please enter a task title.'; valid = false; } if (!dueDate) { $('#dateError').textContent = 'Please choose a due date.'; valid = false; } if (!valid) return; const taskData = { title, description: elements.descriptionInput.value.trim(), priority: elements.priorityInput.value, dueDate }; if (editingTaskId) Object.assign(tasks.find(task => task.id === editingTaskId), taskData); else tasks.unshift({ ...taskData, id: `${Date.now()}-${Math.random()}`, completed: false }); saveTasks(); render(); closeModal(); });
$('#openAddButton').addEventListener('click', () => openModal()); $('#emptyAddButton').addEventListener('click', () => openModal()); $('#closeModal').addEventListener('click', closeModal); $('#cancelButton').addEventListener('click', closeModal); elements.modal.addEventListener('click', event => { if (event.target === elements.modal) closeModal(); }); elements.searchInput.addEventListener('input', render);
document.querySelectorAll('.filter-tab').forEach(button => button.addEventListener('click', () => { activeFilter = button.dataset.filter; document.querySelectorAll('.filter-tab').forEach(tab => tab.classList.toggle('active', tab === button)); render(); })); document.addEventListener('keydown', event => { if (event.key === 'Escape' && !elements.modal.hidden) closeModal(); }); render();
